---
- name: Check if wkhtmltopdf package is installed
  command: dpkg-query -W wkhtmltopdf
  register: wkhtmltopdf_check_deb
  failed_when: wkhtmltopdf_check_deb.rc > 1
  changed_when: wkhtmltopdf_check_deb.rc == 1

- name: Download wkhtmltopdf package from specific url
  get_url:
    url: '{{ item }}'
    dest: "/tmp/wkhtmltopdf.deb"
  with_items:
    - '{{ wkhtmltopdf_download_url }}'
  when: wkhtmltopdf_check_deb.rc == 1

- name: Install wkhtmltopdf package
  apt:
    deb: /tmp/wkhtmltopdf.deb
  when: wkhtmltopdf_check_deb.rc == 1

- name: Remove wkhtmltopdf debian package
  file:
    path: /tmp/wkhtmltopdf.deb
    state: absent
  when: wkhtmltopdf_check_deb.rc == 1
